apiVersion: v1
kind: ConfigMap
metadata:
  name: pkl-argo-cmp-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: pkl-argo-cmp
    spec:
      version: v0.1.0
      init:
        command: ["pkl"]
        args: ["project", "resolve"]
      generate:
        command: ["pkl"]
        args: ["eval", "main.pkl"]
      discover:
        fileName: "./main.pkl"
